version: 0.2

run-as: codebuild-user

env:
  git-credential-helper: no

phases:
  install:
    run-as: codebuild-user
    on-failure: ABORT
    runtime-versions:
      nodejs: 12
    commands:
#        - chown -R 1000:1000 "/root/.npm"
       - npm install
#   pre_build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
#   build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
  
#   post_build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no
# artifacts:
#   files:
#     - location
#     - location
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   enable-symlinks: yes
#   s3-prefix: prefix
