version: 0.2

run-as: codebuild-user

env:
  git-credential-helper: no

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      nodejs: 12
    commands:
#        - chown -R 1000:1000 "/root/.npm"
#        - npm install -g --unsafe-perm=true --allow-root
      - npm -v
      - npm cache clean --force
      - npm install -g npm@latest
#   pre_build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
#   build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
  
#   post_build:
#     run-as: ec2-user
#     on-failure: ABORT
#     commands:
#       - command
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no
artifacts:
  files:
    - '**/*'
  name: artifact-name
  discard-paths: yes
  base-directory: base_dir
  enable-symlinks: yes
  s3-prefix: Build
