name: CalculatorJS-GH-Action

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  npmLocalBuildJob:
    name: npmLocalBuildJob
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Local Test Build
      run: |
        npm config set fund false --location=global  
        npm install --package-lock
        npm run-script build
        npm test
        npm prune --production

  dockerBuildAndPushJob:
    name: dockerBuildAndPushJob
    runs-on: ubuntu-latest
    needs: npmLocalBuildJob
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Get application version from package.json
        run: |
          ls -lrth /home/runner/work/calculator-app-nodejs/calculator-app-nodejs
          APP_VERSION=$(jq --raw-output .version ../package.json)
          echo ${APP_VERSION}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Scrape build info
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          repository: dmfpython/calculator-example-app
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_VERSION_TAG=${{ env.APP_VERSION }}
            GIT_COMMIT_MESSAGE=${{ github.event.head_commit.message }}
            GIT_VERSION_HASH=${{ github.sha }}
        # env:
        #   APP_VERSION: $()
