name: NodeJS with Webpack

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  npmLocalBuildJob:
    name: npmLocalBuildJob
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Local Test Build
      run: |
        npm config set fund false --location=global  
        npm install --package-lock
        npm run-script build
        npm test
        npm prune --production

  dockerBuildAndPushJob:
    runs-on: ubuntu-latest
    needs: npmLocalBuildJob
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Check docker version
        run: docker --version
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dmfpython/calculator-example-app:latest
